[toolchain]
channel = "nightly"
components = [
    "rustc",
    "rust-std",
    "rust-src",
    "rust-analyzer",
    "rust-docs",
    "rustfmt",
    "cargo",
    "clippy",
    "llvm-tools-preview"
]
[unstable]
coverage_attribute = true